### ISSUE TITLE
No Tomb earn from Tshare stake

### ISSUE THREAD

**Issue by Lertsuwat** [tombfinance/tombfinance-frontend#39]
I haven't gotten Tomb earn from Tshare stake for almost 2 days. What happen?

**Comment by bitnic69** [comment]
Hello Lertsuwat,

Thanks for reaching out. To answer your question, nothing has happened, it is working as it is supposed to. The staked Tshare in Masonry is part of the pegging mechanism to increase the Tomb supply when needed. This mechanism will kick in when Tomb TWAP is over 1.01 at the end of the epoch.

Greetings.

**Comment by Lertsuwat** [comment]
Thanks. I will wait and see
