### ISSUE TITLE
Homepage buttons not aligned properly on mobile

### ISSUE THREAD

**Issue by OGBoogieTomb** [tombfinance/tombfinance-frontend#5]
### Issue description
When navigating to https://tomb.finance on mobile these 4 buttons align incorrectly on mobile device while they display properly on desktop web.
 
![image](https://user-images.githubusercontent.com/85199909/122974599-d197bb00-d392-11eb-82ba-e0a787dc4fb9.png)

### Expectation
The grey coloured buttons need to be aligned properly with the purple ones.

**Comment by coderfinn** [comment]
I've created a pull request #12 for this :-)

**Comment by OGBoogieTomb** [comment]
Hey @coderfinn sorry for the delay and really thanks for the contribution. Will have a look later tonight. 🙌

**Comment by OGBoogieTomb** [comment]
Solved after merging #12
