### ISSUE TITLE
Metamask mobile does not work for android users

### ISSUE THREAD

**Issue by OGBoogieTomb** [tombfinance/tombfinance-frontend#6]
### Active Bounty
Tomb amount : 1000 $TOMB

### Background information
A big amount of tomb.finance investors are using mobile to connect to their wallets and interact with their staked assets. Mobile users can use their browser (chrome, safari etc) of choice or metamask's built in browser to visit the website which is using the [use-wallet](https://github.com/aragon/use-wallet) library as an interface to interact with the users wallets. 

### Issue description
There have been various reports from our users that when they are trying to connect their wallet on the website via `metamask`'s build in browser the buttons are unresponsive and there is no prompt taking them to metamask to connect.

The issue has being mainly reported by users who use android and metamask built in browser.
![Screenshot 2021-06-22 at 20 05 19](https://user-images.githubusercontent.com/85199909/122976913-305e3400-d395-11eb-95c3-acbf5dfa4c19.png)

### Expected functionality
When users click either  `metamask` or `walletConnect -> connect/metamask` they should be deeplinked to the metamask application installed on their mobile phone to approve the connection.

**Comment by al5ina5** [comment]
Hi!

I just opened a PR to fix this.

The PR:
— Fixed a bug that caused the wallet connection modal to leak on small screens.
— Fixed a bug that caused the Connect MetaMask button on MetaMask Android to fail.

Tested 2x by 2 members. Connecting your wallet on Android devices now works successfully.

 A live preview can be tested here: https://github.com/tombfinance/tombfinance-frontend/pull/9

🥳

**Comment by OGBoogieTomb** [comment]
Fixed by a series of pull requests ( #11 , #10 ) and a long discussion in discord in collaborations with both @al5ina5 and a discord community member `@kinuHero`.
The bounty was agreed to be split between the 2 contributors on a 60/40 ratio.
Bounty payment transactions for reference:

`@al5ina5`'s payment: [transaction-#1](https://ftmscan.com/tx/0xf4c50cb24674b2be93e0f231164852dbd69664f5f70ac4e2021e40f40614eb32)
`@kinuHero`'s payment: [transaction-#2](https://ftmscan.com/tx/0x353000d5ee8b0fe498ef589a7f61e6a40d7b54aaee0c88aaf7ae96d95f8f46e2
)
